# UI Helper Functions
# Functions for UI elements, reactive values, and display formatting

#' Create dynamic trait input UI
#' @importFrom shiny tagList wellPanel fileInput numericInput fluidRow column
#' @param n Number of traits
#' @return UI elements for trait inputs
create_trait_inputs <- function(n) {
  tagList(
    lapply(seq_len(n), function(i) {
      wellPanel(
        fileInput(paste0("trait_file_", i), paste("EBVs for trait", i)),
        numericInput(paste0("trait_weight_", i), paste("Relative weight for Trait", i),
                     value = round(1 / n, 3), min = 0, max = 1, step = 0.01)
      )
    })
  )
}

#' Create OCS trait input UI
#' @importFrom shiny fileInput numericInput fluidRow column
#' @param n Number of traits
#' @return UI elements for OCS trait inputs
create_ocs_trait_inputs <- function(n) {
  lapply(1:n, function(i) {
    fluidRow(
      column(6, fileInput(paste0("ocs_trait_file_", i), paste("Upload EBV File", i))),
      column(6, numericInput(paste0("ocs_trait_weight_", i), paste("Weight for Trait", i),
                             value = round(1 / n, 2), min = 0, max = 1, step = 0.01))
    )
  })
}

#' Generate package status text
#' @return Formatted status text for display
generate_package_status <- function() {
  optisel_flag <- exists("optisel_available") && isTRUE(optisel_available)
  fallback_flag <- exists("custom_ocs_available") && isTRUE(custom_ocs_available)
  quadprog_flag <- exists("quadprog_available") && isTRUE(quadprog_available)
  
  if (optisel_flag) {
    status_text <- "✅ Optimum Contribution Selection: Ready\n📦 Current solver: optiSel"
  } else if (fallback_flag && quadprog_flag) {
    status_text <- "✅ Optimum Contribution Selection: Ready\n📦 Current solver: quadprog fallback"
    if (exists("is_webr") && is_webr) {
      status_text <- paste(status_text, "\nℹ️ optiSel not available in WebR", sep = "")
    } else {
      status_text <- paste(status_text, "\nℹ️ optiSel not installed", sep = "")
    }
  } else if (fallback_flag && !quadprog_flag) {
    status_text <- "❌ Optimum Contribution Selection: Not Ready\n⚠️ quadprog package required for fallback\nℹ️ Install with: install.packages('quadprog')"
  } else {
    status_text <- "❌ Optimum Contribution Selection: Not Ready\n⚠️ Neither optiSel nor fallback available"
  }
  
  status_text
}

#' Check if WebR is detected
#' @return TRUE if WebR environment detected
is_webr_environment <- function() {
  exists("is_webr") && is_webr
}

#' Format kinship and EBV results for display
#' @importFrom dplyr left_join relocate mutate filter
#' @param kinship_results Kinship analysis results
#' @param ebv_results EBV analysis results
#' @param thresh Kinship threshold
#' @return Formatted results for display
format_kinship_ebv_results <- function(kinship_results, ebv_results, thresh) {
  if (!is.null(kinship_results) && !is.null(ebv_results)) {
    full_results <- left_join(kinship_results$results, ebv_results$results, by = c("Female", "Male"))
  } else if (!is.null(ebv_results)) {
    full_results <- relocate(mutate(ebv_results$results, Kinship = NA), Kinship, .after = EBV)
  } else {
    return(NULL)
  }
  
  filt_results_table <- full_results %>%
    filter(EBV > 0, (is.na(Kinship) | Kinship < thresh))
  
  filt_results_matrix <- full_results %>%
    mutate(EBV = ifelse(EBV <= 0 | (!is.na(Kinship) & Kinship >= thresh), NA, EBV))
  
  list(
    table_results = filt_results_table,
    matrix_results = filt_results_matrix,
    full_results = full_results
  )
}

#' Create Excel workbook for kinship and EBV results
#' @importFrom openxlsx createWorkbook addWorksheet writeData
#' @param table_results Filtered table results
#' @param matrix_results Matrix results with masked values
#' @param full_results Complete results
#' @return Workbook object ready for saving
create_kinship_ebv_workbook <- function(table_results, matrix_results, full_results) {
  wb <- createWorkbook()
  
  addWorksheet(wb, "README")
  readme_text <- c(
    "This Excel file contains two data sheets generated by the app:",
    "",
    "1. Filtered Results - Table:",
    "   - Only crosses with positive EBVs and kinship below the selected threshold are included.",
    "   - Crosses failing these criteria are completely removed from this table.",
    "",
    "2. EBV Matrix - Masked:",
    "   - Shows all possible male-female crosses with EBV values.",
    "   - EBVs for crosses with negative values or kinship above the threshold are blank (hidden) in the matrix.",
    "",
    "This distinction allows detailed matrix views while keeping the filtered table clean for analysis."
  )
  writeData(wb, "README", readme_text)
  
  addWorksheet(wb, "Filtered Results")
  writeData(wb, "Filtered Results", table_results, rowNames = TRUE)
  
  addWorksheet(wb, "EBV Matrix")
  
  m_ids <- unique(full_results$Male)
  f_ids <- unique(full_results$Female)
  mat_for_excel <- matrix(NA_real_, nrow = length(m_ids), ncol = length(f_ids), dimnames = list(m_ids, f_ids))
  
  for (i in seq_len(nrow(matrix_results))) {
    m <- matrix_results$Male[i]
    f <- matrix_results$Female[i]
    mat_for_excel[m, f] <- matrix_results$EBV[i]
  }
  
  writeData(wb, "EBV Matrix", mat_for_excel, rowNames = TRUE)
  wb
}

#' Validate file uploads
#' @importFrom readr read_table
#' @param file Uploaded file object
#' @param required_cols Required column names
#' @param file_type Type of file for error messages
#' @return TRUE if valid, throws error if invalid
validate_file_upload <- function(file, required_cols = NULL, file_type = "file") {
  if (is.null(file)) stop(paste("❌ No", file_type, "uploaded"))
  if (file$size == 0) stop(paste("❌", file_type, "file is empty"))
  
  tryCatch({
    df <- read_table(file$datapath)
    if (nrow(df) == 0) stop(paste("❌", file_type, "file contains no data"))
    
    if (!is.null(required_cols)) {
      missing_cols <- setdiff(required_cols, names(df))
      if (length(missing_cols) > 0) stop(paste("❌", file_type, "missing required columns:", paste(missing_cols, collapse = ", ")))
    }
    TRUE
  }, error = function(e) stop(paste("❌ Error reading", file_type, ":", e$message)))
}

#' Generate user feedback messages
#' @param success Whether operation was successful
#' @param message Success or error message
#' @param operation Type of operation performed
#' @return Formatted feedback message
generate_feedback <- function(success, message, operation) {
  if (success) paste0("✅ ", operation, " completed successfully: ", message)
  else paste0("❌ ", operation, " failed: ", message)
}
